
package com.secusociale.portail.service.soap.demandeAttestationReguralite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CmGetAttestationRegularitePortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetAttestationRegularite")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CmGetAttestationRegularitePortType {


    /**
     * 
     * @param body
     * @throws CmGetAttestationRegulariteFault
     */
    @WebMethod(operationName = "CmGetAttestationRegularite", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetAttestationRegularite")
    public void cmGetAttestationRegularite(
        @WebParam(name = "CmGetAttestationRegularite", targetNamespace = "http://oracle.com/CmGetAttestationRegularite.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CmGetAttestationRegularite> body)
        throws CmGetAttestationRegulariteFault
    ;

}
