
package com.secusociale.portail.service.soap.demandeAttestationReguralite;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.secusociale.portail.service.PortailConstant;


/**
 * CmGetAttestationRegularite version 2: get attestation regularit�
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CmGetAttestationRegulariteService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetAttestationRegularite", wsdlLocation =  PortailConstant.ATTESTATION_REGU_WSDL)
public class CmGetAttestationRegulariteService
    extends Service
{

    private final static URL CMGETATTESTATIONREGULARITESERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETATTESTATIONREGULARITESERVICE_EXCEPTION;
    private final static QName CMGETATTESTATIONREGULARITESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetAttestationRegularite", "CmGetAttestationRegulariteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PortailConstant.ATTESTATION_REGU_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETATTESTATIONREGULARITESERVICE_WSDL_LOCATION = url;
        CMGETATTESTATIONREGULARITESERVICE_EXCEPTION = e;
    }

    public CmGetAttestationRegulariteService() {
        super(__getWsdlLocation(), CMGETATTESTATIONREGULARITESERVICE_QNAME);
    }

    public CmGetAttestationRegulariteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETATTESTATIONREGULARITESERVICE_QNAME, features);
    }

    public CmGetAttestationRegulariteService(URL wsdlLocation) {
        super(wsdlLocation, CMGETATTESTATIONREGULARITESERVICE_QNAME);
    }

    public CmGetAttestationRegulariteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETATTESTATIONREGULARITESERVICE_QNAME, features);
    }

    public CmGetAttestationRegulariteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmGetAttestationRegulariteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CmGetAttestationRegularitePortType
     */
    @WebEndpoint(name = "CmGetAttestationRegularitePort")
    public CmGetAttestationRegularitePortType getCmGetAttestationRegularitePort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetAttestationRegularite", "CmGetAttestationRegularitePort"), CmGetAttestationRegularitePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmGetAttestationRegularitePortType
     */
    @WebEndpoint(name = "CmGetAttestationRegularitePort")
    public CmGetAttestationRegularitePortType getCmGetAttestationRegularitePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetAttestationRegularite", "CmGetAttestationRegularitePort"), CmGetAttestationRegularitePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETATTESTATIONREGULARITESERVICE_EXCEPTION!= null) {
            throw CMGETATTESTATIONREGULARITESERVICE_EXCEPTION;
        }
        return CMGETATTESTATIONREGULARITESERVICE_WSDL_LOCATION;
    }

}
