
package com.secusociale.portail.service.soap.demandeImmatriculation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.secusociale.portail.service.PortailConstant;


/**
 * IMMATRICULATION_INBOUND version 4: IMMATRICULATION INBOUND SERVICE
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IMMATRICULATION_INBOUNDService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMATRICULATION_INBOUND", wsdlLocation =  PortailConstant.IMMATRICULATION_WSDL)
public class IMMATRICULATIONINBOUNDService
    extends Service
{

    private final static URL IMMATRICULATIONINBOUNDSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMMATRICULATIONINBOUNDSERVICE_EXCEPTION;
    private final static QName IMMATRICULATIONINBOUNDSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMATRICULATION_INBOUND", "IMMATRICULATION_INBOUNDService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PortailConstant.IMMATRICULATION_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMMATRICULATIONINBOUNDSERVICE_WSDL_LOCATION = url;
        IMMATRICULATIONINBOUNDSERVICE_EXCEPTION = e;
    }

    public IMMATRICULATIONINBOUNDService() {
        super(__getWsdlLocation(), IMMATRICULATIONINBOUNDSERVICE_QNAME);
    }

    public IMMATRICULATIONINBOUNDService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMMATRICULATIONINBOUNDSERVICE_QNAME, features);
    }

    public IMMATRICULATIONINBOUNDService(URL wsdlLocation) {
        super(wsdlLocation, IMMATRICULATIONINBOUNDSERVICE_QNAME);
    }

    public IMMATRICULATIONINBOUNDService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMMATRICULATIONINBOUNDSERVICE_QNAME, features);
    }

    public IMMATRICULATIONINBOUNDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMMATRICULATIONINBOUNDService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMMATRICULATIONINBOUNDPortType
     */
    @WebEndpoint(name = "IMMATRICULATION_INBOUNDPort")
    public IMMATRICULATIONINBOUNDPortType getIMMATRICULATIONINBOUNDPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMATRICULATION_INBOUND", "IMMATRICULATION_INBOUNDPort"), IMMATRICULATIONINBOUNDPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMMATRICULATIONINBOUNDPortType
     */
    @WebEndpoint(name = "IMMATRICULATION_INBOUNDPort")
    public IMMATRICULATIONINBOUNDPortType getIMMATRICULATIONINBOUNDPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMATRICULATION_INBOUND", "IMMATRICULATION_INBOUNDPort"), IMMATRICULATIONINBOUNDPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMMATRICULATIONINBOUNDSERVICE_EXCEPTION!= null) {
            throw IMMATRICULATIONINBOUNDSERVICE_EXCEPTION;
        }
        return IMMATRICULATIONINBOUNDSERVICE_WSDL_LOCATION;
    }

}
