
package com.secusociale.portail.service.soap.demandeImmatriculation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMMATRICULATION_INBOUNDPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMATRICULATION_INBOUND")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMMATRICULATIONINBOUNDPortType {


    /**
     * 
     * @param body
     * @throws IMMATRICULATIONINBOUNDFault
     */
    @WebMethod(operationName = "IMMATRICULATION_INBOUND", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMATRICULATION_INBOUND")
    public void immatriculationINBOUND(
        @WebParam(name = "IMMATRICULATION_INBOUND", targetNamespace = "http://oracle.com/IMMATRICULATION_INBOUND.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<IMMATRICULATIONINBOUND> body)
        throws IMMATRICULATIONINBOUNDFault
    ;

}
