import { Moment } from 'moment';
import { RepresentantLegal } from 'app/shared/model/representant-legal.model';
import { User } from 'app/core/user/user.model';
import { Declaration } from 'app/shared/model/declaration.model';
import { Employe } from 'app/shared/model/employe.model';
import { Document } from 'app/shared/model/document.model';

export class FormData {
  id?: number;
  regType?: string;
  employerType?: string;
  typeEtablissement?: string;
  employerName?: string;
  hqId?: string;
  nineaNumber?: string;
  ninetNumber?: string;
  compagnyOriginId?: string;
  legalStatus?: string;
  taxId?: string;
  taxIdDate?: Moment;
  tradeRegisterNumber?: string;
  tradeRegisterDate?: Moment;
  dateOfInpsection?: Moment;
  dateOfFirtHire?: Moment;
  shortName?: string;
  businessSector?: string;
  mainLineOfBusiness?: string;
  noOfWorkersInGenScheme?: number;
  noOfWorkersInBasicScheme?: number;
  region?: string;
  department?: string;
  arondissement?: string;
  commune?: string;
  qartier?: string;
  address?: string;
  postboxNo?: string;
  telephone?: string;
  email?: string;
  website?: string;
  zoneCss?: string;
  zoneIpres?: string;
  sectorCss?: string;
  sectorIpres?: string;
  agencyCss?: string;
  agencyIpres?: string;
  employerRegistrationFormId?: string;
  employeeRegistrationFormId?: string;
  processFlowId?: string;
  statutDossier?: string;
  statutImmatriculation?: boolean;
  representantLegal?: RepresentantLegal;
  user?: User;
  declarations?: Declaration[];
  employes?: Employe[];
  documents?: Document[];
}
