
package com.secusociale.portail.service.soap.certificatImmatriculation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.secusociale.portail.service.PortailConstant;


/**
 * CmGetCertificatImmatriculation version 2: get certificat immatriculation
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CmGetCertificatImmatriculationService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetCertificatImmatriculation", wsdlLocation = PortailConstant.CERTIFICAT_IMMAT_WSDL)
public class CmGetCertificatImmatriculationService
    extends Service
{

    private final static URL CMGETCERTIFICATIMMATRICULATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETCERTIFICATIMMATRICULATIONSERVICE_EXCEPTION;
    private final static QName CMGETCERTIFICATIMMATRICULATIONSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetCertificatImmatriculation", "CmGetCertificatImmatriculationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PortailConstant.CERTIFICAT_IMMAT_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETCERTIFICATIMMATRICULATIONSERVICE_WSDL_LOCATION = url;
        CMGETCERTIFICATIMMATRICULATIONSERVICE_EXCEPTION = e;
    }

    public CmGetCertificatImmatriculationService() {
        super(__getWsdlLocation(), CMGETCERTIFICATIMMATRICULATIONSERVICE_QNAME);
    }

    public CmGetCertificatImmatriculationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETCERTIFICATIMMATRICULATIONSERVICE_QNAME, features);
    }

    public CmGetCertificatImmatriculationService(URL wsdlLocation) {
        super(wsdlLocation, CMGETCERTIFICATIMMATRICULATIONSERVICE_QNAME);
    }

    public CmGetCertificatImmatriculationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETCERTIFICATIMMATRICULATIONSERVICE_QNAME, features);
    }

    public CmGetCertificatImmatriculationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmGetCertificatImmatriculationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CmGetCertificatImmatriculationPortType
     */
    @WebEndpoint(name = "CmGetCertificatImmatriculationPort")
    public CmGetCertificatImmatriculationPortType getCmGetCertificatImmatriculationPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetCertificatImmatriculation", "CmGetCertificatImmatriculationPort"), CmGetCertificatImmatriculationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmGetCertificatImmatriculationPortType
     */
    @WebEndpoint(name = "CmGetCertificatImmatriculationPort")
    public CmGetCertificatImmatriculationPortType getCmGetCertificatImmatriculationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGetCertificatImmatriculation", "CmGetCertificatImmatriculationPort"), CmGetCertificatImmatriculationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETCERTIFICATIMMATRICULATIONSERVICE_EXCEPTION!= null) {
            throw CMGETCERTIFICATIMMATRICULATIONSERVICE_EXCEPTION;
        }
        return CMGETCERTIFICATIMMATRICULATIONSERVICE_WSDL_LOCATION;
    }

}
