
package com.secusociale.portail.service.soap.declaration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DNS_INBOUND_SERVICEPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DNS_INBOUND_SERVICE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DNSINBOUNDSERVICEPortType {


    /**
     * 
     * @param body
     * @throws DNSINBOUNDSERVICEFault
     */
    @WebMethod(operationName = "DNS_INBOUND_SERVICE", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DNS_INBOUND_SERVICE")
    public void dnsINBOUNDSERVICE(
        @WebParam(name = "DNS_INBOUND_SERVICE", targetNamespace = "http://oracle.com/DNS_INBOUND_SERVICE.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<DNSINBOUNDSERVICE> body)
        throws DNSINBOUNDSERVICEFault
    ;

}
