
package com.secusociale.portail.service.soap.declaration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.secusociale.portail.service.PortailConstant;


/**
 * DNS_INBOUND_SERVICE version 3: DNS_INBOUND_SERVICE
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DNS_INBOUND_SERVICEService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DNS_INBOUND_SERVICE", wsdlLocation =  PortailConstant.DECLARATION_WSDL)
public class DNSINBOUNDSERVICEService
    extends Service
{

    private final static URL DNSINBOUNDSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DNSINBOUNDSERVICESERVICE_EXCEPTION;
    private final static QName DNSINBOUNDSERVICESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DNS_INBOUND_SERVICE", "DNS_INBOUND_SERVICEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL( PortailConstant.DECLARATION_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DNSINBOUNDSERVICESERVICE_WSDL_LOCATION = url;
        DNSINBOUNDSERVICESERVICE_EXCEPTION = e;
    }

    public DNSINBOUNDSERVICEService() {
        super(__getWsdlLocation(), DNSINBOUNDSERVICESERVICE_QNAME);
    }

    public DNSINBOUNDSERVICEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DNSINBOUNDSERVICESERVICE_QNAME, features);
    }

    public DNSINBOUNDSERVICEService(URL wsdlLocation) {
        super(wsdlLocation, DNSINBOUNDSERVICESERVICE_QNAME);
    }

    public DNSINBOUNDSERVICEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DNSINBOUNDSERVICESERVICE_QNAME, features);
    }

    public DNSINBOUNDSERVICEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DNSINBOUNDSERVICEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DNSINBOUNDSERVICEPortType
     */
    @WebEndpoint(name = "DNS_INBOUND_SERVICEPort")
    public DNSINBOUNDSERVICEPortType getDNSINBOUNDSERVICEPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DNS_INBOUND_SERVICE", "DNS_INBOUND_SERVICEPort"), DNSINBOUNDSERVICEPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DNSINBOUNDSERVICEPortType
     */
    @WebEndpoint(name = "DNS_INBOUND_SERVICEPort")
    public DNSINBOUNDSERVICEPortType getDNSINBOUNDSERVICEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DNS_INBOUND_SERVICE", "DNS_INBOUND_SERVICEPort"), DNSINBOUNDSERVICEPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DNSINBOUNDSERVICESERVICE_EXCEPTION!= null) {
            throw DNSINBOUNDSERVICESERVICE_EXCEPTION;
        }
        return DNSINBOUNDSERVICESERVICE_WSDL_LOCATION;
    }

}
